version: '3'

services:
  app:
    container_name: jira
    image: jira-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    build:
      context: ./
      dockerfile: Dockerfile.postgres

    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: jira
      POSTGRES_USERNAME: jira
      POSTGRES_PASSWORD: JiraRush
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
